config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :ous
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  # get '/about/:id', to: 'home#about', as: 'portal'
  # get '/about/:id/delete', to: 'portals#delete'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services
    root to: "users#index"
  end

  namespace :madmin do
    namespace :active_storage do
      resources :blobs
    end
    namespace :active_storage do
      resources :variant_records
    end
    resources :announcements
    resources :notifications
    resources :users
    resources :services
    namespace :active_storage do
      resources :attachments
    end
    root to: "dashboard#show"
  end
end

  get '/portals/export', to: 'portals#export'
  resources :about, only: [:show, :delete]
  resources :portals
  resources :places
  resources :actives
  resources :districts
  resources :formats
  resources :auds
  resources :site_infos
  resources :my_events

  get '/events/export', to: 'events#export'
  resources :events

  resources :calendar, only: [:index]
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ou.rb
class Ou < ApplicationRecord
  has_many :user
end

app/controllers/ous_controller.rb
class OusController < ApplicationController
  before_action :set_ou, only: %i[ show edit update destroy ]

  # GET /ous or /ous.json
  def index
    @ous = Ou.all
  end

  # GET /ous/1 or /ous/1.json
  def show
  end

  # GET /ous/new
  def new
    @ou = Ou.new
  end

  # GET /ous/1/edit
  def edit
  end

  # POST /ous or /ous.json
  def create
    @ou = Ou.new(ou_params)

    respond_to do |format|
      if @ou.save
        format.html { redirect_to @ou, notice: "Ou was successfully created." }
        format.json { render :show, status: :created, location: @ou }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ou.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ous/1 or /ous/1.json
  def update
    respond_to do |format|
      if @ou.update(ou_params)
        format.html { redirect_to @ou, notice: "Ou was successfully updated." }
        format.json { render :show, status: :ok, location: @ou }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ou.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ous/1 or /ous/1.json
  def destroy
    @ou.destroy
    respond_to do |format|
      format.html { redirect_to ous_url, notice: "Ou was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ou
      @ou = Ou.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ou_params
      params.require(:ou).permit(:name)
    end
end

app/views/ous/_edit.html.haml
%h4= t("ous.actions.edit")
= form_for @ou do |f|
  .form-group
    %table
      %tr
        %td= t("ous.name")
        %td= f.text_field :name, autofocus: false, ouholder: t("ous.name"), class: 'form-control'
      %tr
        %td{:colspan=>2}
          .form-actions
            = f.submit @ou.new_record? ? t("buttons.create") : t("buttons.save"), :class => 'btn btn-primary btn-with-tooltip',"data-original-title" => t("messages.tooltips.save"),"data-oument" => "bottom"
            = link_to t("buttons.cancel"), {:action => 'index'}

app/views/ous/_list.html.haml
-if @ous.count > 20
  .flickr_pagination
    = will_paginate @ous

%table.table.table-striped
  %thead
    -if current_user.admin?
      %th= t("ous.id")
    %th= t("ous.name")
    -if current_user.admin?
      %th= t("ous.actions.title")
  %tbody
    - @ous.each do |row|
      -if can? :read, row
        %tr
          -if current_user.admin?
            %td
              = t("ous.id")
              = row.id.to_s
          %td= row.name.to_s
          -if current_user.admin?
            %td
              - if can? :edit, Ou
                = link_to edit_ou_path(row) do
                  = bootstrap_icon "pencil", width: 15, height: 15, fill: "green"
              - if can? :delete, Ou
                = link_to ou_path(row), :method => :delete,  data: { confirm: t('delete_confirm')} do
                  = bootstrap_icon "trash", width: 15, height: 15, fill: "red"

-if @ous.count > 20
  .flickr_pagination
    = will_paginate @ous

-#permit(:name, :description, :contact_fio, :contact_address, :contact_email, :contact_phone)

app/views/ous/edit.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/ous/index.html.haml
.row
  .span9
    %h3.pull-left= t("ous.list.title")
    -# = render_notice
    %span.top-panel-actions
      %table.table.borderless
        %tr
          %td
            = form_tag ous_path, :method => 'get', :id => "ous_search" do
              %p
                = text_field_tag :search, params[:search]
                = button_tag(type: "submit", class: "btn btn-default", :name => nil) do
                  = bootstrap_icon "search", width: 25, height: 25, fill: "blue"
          %td
            - if can? :create, Ou
              = link_to new_ou_path do
                = bootstrap_icon "file-plus", width: 15, height: 15, fill: "blue"
                = "добавить"
            -# - if can? :export, Ou
            -#   = link_to ous_export_path do
            -#     = bootstrap_icon "download", width: 15, height: 15, fill: "blue"

    %span.marks-filter-target
      = render :partial => 'list', :locals => {:legend => t(".title")}

app/views/ous/new.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/ous/show.html.haml
-# -@id=params[:id]
%h1 Наименование проекта
%h2=@ou.name.to_s
%table
  %tr
    %td=t("ous.id")
    %td=@ou.id.to_s
  %tr
    %td=t("ous.name")
    %td=@ou.name
%div
  = link_to "Вернуться", ous_path, :class => "btn btn-primary btn-mini"