config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :ous
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  # get '/about/:id', to: 'home#about', as: 'portal'
  # get '/about/:id/delete', to: 'portals#delete'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services
    root to: "users#index"
  end

  namespace :madmin do
    namespace :active_storage do
      resources :blobs
    end
    namespace :active_storage do
      resources :variant_records
    end
    resources :announcements
    resources :notifications
    resources :users
    resources :services
    namespace :active_storage do
      resources :attachments
    end
    root to: "dashboard#show"
  end
end

  get '/portals/export', to: 'portals#export'
  resources :about, only: [:show, :delete]
  resources :portals
  resources :places
  resources :actives
  resources :districts
  resources :formats
  resources :auds
  resources :site_infos
  resources :my_events

  get '/events/export', to: 'events#export'
  resources :events

  resources :calendar, only: [:index]
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/site_info.rb
class SiteInfo < ApplicationRecord


  self.per_page = 20

  WillPaginate.per_page = 20

  has_one_attached :logo_image
  attr_accessor :delete_logo_image

  has_one_attached :dev_logo_image
  attr_accessor :delete_dev_logo_image


end

app/controllers/site_infos_controller.rb
class SiteInfosController < ApplicationController
  load_and_authorize_resource :instance_name => :item
  before_action :authenticate_user!

  def index
    new
  end

  def new
    @site_info = SiteInfo.all.first
    if !@site_info.nil?
      render :edit
    else
      @site_info = SiteInfo.new
      if !@site_info.nil?
        render :edit
      else
        flash[:success] = t("site_infos.errors.cant_create_new")
        redirect_to root_path
      end
    end
  end


  def show
    @new
  end

  def create
    @site_info = SiteInfo.new(site_info_params)
    if @site_info.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
  end

  def edit
    @site_info = SiteInfo.accessible_by(current_ability).find(params[:id])
  end

  def delete
    SiteInfo.accessible_by(current_ability).find(params[:id]).destroy
    return
  end

  def destroy
    @site_info = SiteInfo.accessible_by(current_ability).find(params[:id])
    @site_info.destroy
    respond_to do |format|
      format.html { redirect_to ates_url, notice: t("site_infos.notice.destroyed") }
      format.json { head :no_content }
    end
    # redirect :action => 'index'
  end

  def update
    @site_info = SiteInfo.accessible_by(current_ability).find params[:id]
    # respond_to do |format|
    if @site_info.update site_info_params
      flash[:success] = t("site_infos.notice.updated")
      redirect_to :action => 'index'
    else
      render :action => 'edit'
    end
  end

  def site_info_params
    params.require(:site_info).permit(:site_name, :dev_site_link, :logo_image,
                                      :delete_logo_image, :dev_logo_image, :delete_dev_logo_image,
                                      :copyright_string, :copyright_string_link1_name, :copyright_string_link1_url,
                                      :copyright_string_link2_name, :copyright_string_link2_url,
                                      :sn_vk, :sn_facebook, :sn_twitter, :sn_ok)
  end

end

app/helpers/site_info_helper.rb
module SiteInfoHelper
end

app/views/site_infos/_edit.html.haml
%h4= t("site_infos.actions.edit")
= form_for @site_info do |f|
  .form-group
    %table
      %tr
        %td= t("site_infos.site_name")
        %td= f.text_field :site_name, autofocus: false, placeholder: t("site_infos.site_name"), class: 'form-control'
      %tr
        %td= t("site_infos.dev_site_link")
        %td= f.text_field :dev_site_link, autofocus: false, placeholder: t("site_infos.dev_site_link"), class: 'form-control'
      %tr
        %td
          = t("site_infos.logo_image")
          -if @site_info.logo_image.attached?
            = image_tag @site_info.logo_image.variant(resize_to_limit: [100, 100])
        %td
          = f.file_field :logo_image, direct_upload: true
          = f.check_box(:delete_logo_image)
          = t("site_infos.delete_file")
      %tr
        %td
          = t("site_infos.dev_logo_image")
          -if @site_info.dev_logo_image.attached?
            = image_tag @site_info.dev_logo_image.variant(resize_to_limit: [100, 100])
        %td
          = f.file_field :dev_logo_image, direct_upload: true
          = f.check_box(:delete_dev_logo_image)
          = t("site_infos.delete_file")
      %tr
        %td= t("site_infos.copyright_string")
        %td= f.text_field :copyright_string, autofocus: false, placeholder: t("site_infos.copyright_string"), class: 'form-control'
      %tr
        %td= t("site_infos.copyright_string_link1_name")
        %td= f.text_field :copyright_string_link1_name, autofocus: false, placeholder: t("site_infos.copyright_string_link1_name"), class: 'form-control'
      %tr
        %td= t("site_infos.copyright_string_link1_url")
        %td= f.text_field :copyright_string_link1_url, autofocus: false, placeholder: t("site_infos.copyright_string_link1_url"), class: 'form-control'
      %tr
        %td= t("site_infos.copyright_string_link2_name")
        %td= f.text_field :copyright_string_link2_name, autofocus: false, placeholder: t("site_infos.copyright_string_link2_name"), class: 'form-control'
      %tr
        %td= t("site_infos.copyright_string_link2_url")
        %td= f.text_field :copyright_string_link2_url, autofocus: false, placeholder: t("site_infos.copyright_string_link2_url"), class: 'form-control'

      %tr
        %td= t("site_infos.sn_vk")
        %td= f.text_field :sn_vk, autofocus: false, placeholder: t("site_infos.sn_vk"), class: 'form-control'
      %tr
        %td= t("site_infos.sn_facebook")
        %td= f.text_field :sn_facebook, autofocus: false, placeholder: t("site_infos.sn_facebook"), class: 'form-control'
      %tr
        %td= t("site_infos.sn_twitter")
        %td= f.text_field :sn_twitter, autofocus: false, placeholder: t("site_infos.sn_twitter"), class: 'form-control'
      %tr
        %td= t("site_infos.sn_ok")
        %td= f.text_field :sn_ok, autofocus: false, placeholder: t("site_infos.sn_ok"), class: 'form-control'

      %tr
        %td{:colspan=>2}
          .form-actions
            = f.submit @site_info.new_record? ? t("buttons.create") : t("buttons.save"), :class => 'btn btn-primary btn-with-tooltip',"data-original-title" => t("messages.tooltips.save"),"data-placement" => "bottom"
            = link_to t("buttons.cancel"), {:action => 'index'}

app/views/site_infos/_list.html.haml
-if @site_infos.count > 20
  .flickr_pagination
    = will_paginate @site_infos

%table.table.table-striped
  %thead
    -if current_user.admin?
      %th= t("site_infos.id")
    %th= t("site_infos.logo_image")
    %th= t("site_infos.name")
    %th= t("site_infos.description")
    %th= t("site_infos.about")
    -if current_user.admin?
      %th= t("site_infos.actions.title")
  %tbody
    - @site_infos.each do |row|
      -if can? :read, row
        %tr
          -if current_user.admin?
            %td
              = t("site_infos.id")
              = row.id.to_s
              %br
                = t("site_infos.created_at")
                = row.created_at.to_s
              %br
                = t("site_infos.updated_at")
                = row.updated_at.to_s
          %td
            = image_tag row.logo_image.variant(resize_to_limit: [100, 100])
            -# - else
            -#   -if row.logo_image.attached?
            -#     = link_to row.logo_image.filename, row.logo_image
            -#   -else
            -#     = t("site_infos.file_is_absent")
          %td= row.name.to_s
          %td= row.description.to_s
          %td= row.about.to_s
          -if current_user.admin?
            %td
              - if can? :edit, SiteInfo
                = link_to edit_site_info_path(row) do
                  = bootstrap_icon "pencil", width: 15, height: 15, fill: "green"
              - if can? :delete, SiteInfo
                = link_to site_info_path(row), :method => :delete,  data: { confirm: t('delete_confirm')} do
                  = bootstrap_icon "trash", width: 15, height: 15, fill: "red"

-if @site_infos.count > 20
  .flickr_pagination
    = will_paginate @site_infos

app/views/site_infos/edit.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/site_infos/index.html.haml
.row
  .span9
    %h3.pull-left= t("site_infos.list.title")
    -# = render_notice
    %span.top-panel-actions
      %table.table.borderless
        %tr
          %td
            = form_tag site_infos_path, :method => 'get', :id => "site_infos_search" do
              %p
                = text_field_tag :search, params[:search]
                = button_tag(type: "submit", class: "btn btn-default", :name => nil) do
                  = bootstrap_icon "search", width: 25, height: 25, fill: "blue"
          %td
            - if can? :create, SiteInfo
              = link_to new_site_info_path do
                = bootstrap_icon "file-plus", width: 15, height: 15, fill: "blue"
                = "добавить"
            -# - if can? :export, SiteInfo
            -#   = link_to site_infos_export_path do
            -#     = bootstrap_icon "download", width: 15, height: 15, fill: "blue"

    %span.marks-filter-target
      = render :partial => 'list', :locals => {:legend => t(".title")}

app/views/site_infos/new.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/site_infos/show.html.haml
-# -@id=params[:id]
%h1 Наименование проекта
%h2=@site_info.name.to_s
%table
  %tr
    %td=t("site_infos.code")
    %td=@site_info.code.to_s
  %tr
    %td=t("site_infos.full_name")
    %td=@site_info.name
%div
  = link_to "Вернуться", site_infos_path, :class => "btn btn-primary btn-mini"