config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :ous
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  # get '/about/:id', to: 'home#about', as: 'portal'
  # get '/about/:id/delete', to: 'portals#delete'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services
    root to: "users#index"
  end

  namespace :madmin do
    namespace :active_storage do
      resources :blobs
    end
    namespace :active_storage do
      resources :variant_records
    end
    resources :announcements
    resources :notifications
    resources :users
    resources :services
    namespace :active_storage do
      resources :attachments
    end
    root to: "dashboard#show"
  end
end

  get '/portals/export', to: 'portals#export'
  resources :about, only: [:show, :delete]
  resources :portals
  resources :places
  resources :actives
  resources :districts
  resources :formats
  resources :auds
  resources :site_infos
  resources :my_events

  get '/events/export', to: 'events#export'
  resources :events

  resources :calendar, only: [:index]
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.haml
-# -@site_info = SiteInfo.all.first
%footer.text-muted.bg-light
  .container
    %span
      ="© #{Date.today.year}"
      -if !@site_info.nil?
        =(@site_info.copyright_string || 'Информация о разработчике не заполнена')
    -if !@site_info.nil?
      %ul.list-inline.mb-0.float-right
        -if !@site_info.copyright_string_link1_name.nil?
          %li.list-inline-item.mr-3= link_to @site_info.copyright_string_link1_name, @site_info.copyright_string_link1_url
        -if !@site_info.copyright_string_link2_name.nil?
          %li.list-inline-item.mr-3= link_to @site_info.copyright_string_link2_name, @site_info.copyright_string_link2_url

app/views/shared/_head.html.haml
-@site_info=SiteInfo.first
-if !@site_info.nil?
  %title= @site_info.site_name
-else
  %title= Rails.configuration.application_name
%meta{:charset => "utf-8"}/
%meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

%table.table-borderless{:style=>"width:100%;"}
  %tr
    %td
      %br
    %td
      .page-header__logo.small-12.medium-3.large-2{"data-v-65f5be38" => ""}
        -if !@site_info.nil?
          %a{:href => "/"}
            = image_tag @site_info.logo_image.variant(resize_to_limit: [100, 100])
    %td
      .page-header__title.medium-9.large-10.show-for-medium{"data-v-65f5be38" => ""}
        %span.page-header__title-main{"data-v-65f5be38" => ""}
          -if !@site_info.nil?
            =@site_info.site_name
          -else
            =Rails.configuration.application_name
    %td
      -if !@site_info.nil?
        %a{:href => @site_info.dev_site_link.to_s, :target => "_blank"}
          .page-header__dogm-logo.small-6.medium-4.large-2.show-for-large
            -if !@site_info.nil?
              = image_tag @site_info.dev_logo_image.variant(resize_to_limit: [100, 100])

app/views/shared/_navbar.html.haml
- if user_masquerade?
  .alert.alert-warning.text-center
    Вы вошли как
    %b
      = current_user.name
      (#{current_user.email})
    = link_to back_masquerade_path(current_user) do
      = icon("fas", "times")
      Logout
%nav.navbar.navbar-expand-md.navbar-light.bg-light
  .container
    - @site_info = SiteInfo.all.first
    = link_to "Главная", root_path, class: "navbar-brand"
    %button.navbar-toggler{"aria-controls" => "navbarsExample04", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarMain", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarMain.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto.mt-2.mt-md-0
      %ul.navbar-nav
        %li.nav-item= link_to "Все проекты", root_path, class: "nav-link"
        %li.nav-item= link_to "Календарь мероприятий", calendar_index_path, class: "nav-link"
        %li.nav-item= link_to "Архив", '/calendar?filterrific[search_query]=&filterrific[events_params][portals]=&filterrific[events_params][districts]=&filterrific[events_params][places]=&filterrific[events_params][actives]=&filterrific[events_params][auds]=&filterrific[events_params][with_created_at_gte]=2021-01-01&commit=Применить фильтр', class: "nav-link"
        - if user_signed_in?
          -#%li.nav-item
          -#  = link_to notifications_path, class: "nav-link" do
          -#    %span
          -#      %i.far.fa-bell{"aria-hidden" => "true"}
          %li.nav-item.dropdown
            = link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do
              = image_tag avatar_path(current_user, size: 40), height: 20, width: 20, class: "rounded"
            #nav-account-dropdown.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbar-dropdown"}
              - if current_user.admin? && respond_to?(:admin_root_path)
                = link_to "Проекты", portals_path, class: "dropdown-item"
                = link_to "Образовательные организации", ous_path, class: "dropdown-item"
                = link_to "Места проведения", places_path, class: "dropdown-item"
                = link_to "Типы активностей", actives_path, class: "dropdown-item"
                = link_to "Округа", districts_path, class: "dropdown-item"
                = link_to "Форматы проведения", formats_path, class: "dropdown-item"
                = link_to "Целевые аудитории", auds_path, class: "dropdown-item"
                %hr
                = link_to "Информация о сайте", site_infos_path, class: "dropdown-item"
                = link_to t("navigation.admin_area"), admin_root_path, class: "dropdown-item"
                %hr
              -if (current_user.admin? && respond_to?(:admin_root_path)) or current_user.publisher_role?
                = link_to "Мероприятия", events_path, class: "dropdown-item"
              = link_to "Мои мероприятия", my_events_path, class: "dropdown-item"
              %hr
              = link_to "Настройки аккаунта", edit_user_registration_path, class: "dropdown-item"
              .dropdown-divider
              = link_to "Выйти", destroy_user_session_path, method: :delete, class: "dropdown-item"
        - else
          -#%li.nav-item= link_to "Личный кабинет", new_user_registration_path, class: "nav-link"
          %li.nav-item= link_to "Личный кабинет", new_user_session_path, class: "nav-link"

app/views/shared/_notices.html.haml
- flash.each do |msg_type, message|
  %div{:class => "alert #{bootstrap_class_for(msg_type)}"}
    .container
      %button.close{"data-dismiss" => "alert"}
        %span ×
      = message