config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :ous
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  # get '/about/:id', to: 'home#about', as: 'portal'
  # get '/about/:id/delete', to: 'portals#delete'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services
    root to: "users#index"
  end

  namespace :madmin do
    namespace :active_storage do
      resources :blobs
    end
    namespace :active_storage do
      resources :variant_records
    end
    resources :announcements
    resources :notifications
    resources :users
    resources :services
    namespace :active_storage do
      resources :attachments
    end
    root to: "dashboard#show"
  end
end

  get '/portals/export', to: 'portals#export'
  resources :about, only: [:show, :delete]
  resources :portals
  resources :places
  resources :actives
  resources :districts
  resources :formats
  resources :auds
  resources :site_infos
  resources :my_events

  get '/events/export', to: 'events#export'
  resources :events

  resources :calendar, only: [:index]
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/my_event.rb
class MyEvent < ApplicationRecord
  include PgSearch::Model

  belongs_to :user
  belongs_to :event

  self.per_page = 10

  def self.search(search)
    if search
      MyEvent.joins("join events on events.id = my_events.event_id").where('events.name LIKE ?', "%#{search}%").all
    end
  end

end

app/controllers/my_events_controller.rb
class MyEventsController < ApplicationController
  load_and_authorize_resource :instance_name => :item
  before_action :authenticate_user!
  before_action :fill_directories

  def index
    @my_events = MyEvent.accessible_by(current_ability).paginate(page: params[:page]).order('id DESC')

    if params[:search]
      @my_events = @my_events.search(params[:search]).order("created_at DESC")
    else
      @my_events = @my_events.all.order('created_at DESC')
    end

  end

  def new
    @my_event = MyEvent.new
    if !@my_event.nil?
      render :edit
    else
      flash[:error] = t("my_events.errors.cant_create_new")
      redirect_to :action => 'index'
    end
  end

  def show
    @my_event = MyEvent.accessible_by(current_ability).find(params[:id])
  end

  def create
    @my_event = MyEvent.new(my_event_params)
    if !@my_event.event.nil?
      if @my_event.event.can_registered
        if @my_event.save
          redirect_to :action => 'index'
        else
          render :action => 'new'
        end
      else
        flash[:error] = t("my_events.errors.cant_create_new_max_participants")
        render :action => 'new'
      end
    end
  end

  def edit
    @my_event = MyEvent.accessible_by(current_ability).find(params[:id])
  end

  def delete
    MyEvent.accessible_by(current_ability).find(params[:id]).destroy
    return
  end

  def destroy
    @my_event = MyEvent.accessible_by(current_ability).find(params[:id])
    @my_event.destroy
    respond_to do |format|
      format.html { redirect_to my_events_url, notice: t("my_events.notice.destroyed") }
      format.json { head :no_content }
    end
    # redirect :action => 'index'
  end

  def update
    @my_event = MyEvent.accessible_by(current_ability).find params[:id]
    # respond_to do |format|
    if @my_event.update my_event_params
      flash[:success] = t("my_events.notice.updated")
      redirect_to :action => 'index'
    else
      render :action => 'edit'
    end
  end

  def my_event_params
    params.require(:my_event).permit(:event_id, :user_id)
  end

  def fill_directories
    @events = Event.all.where("events.date >= now() or events.date is NULL")
  end

end

app/views/my_events/_edit.html.haml
%h4= t("my_events.actions.edit")
-event_def = params[:event]
-if @my_event.event_id.nil?
  -@my_event.event_id = event_def.to_i
-if @my_event.user_id.nil?
  -@my_event.user_id =  @current_user.id.to_i

= form_for @my_event do |f|
  .form-group
    %table
      %tr
        %td= t("my_events.user")
        -if current_user.admin? # or current_user.publisher_role?
          %td=f.number_field :user_id
        -else
          %td= @current_user.email
          =f.hidden_field :user_id, :value => @current_user.id
      %tr
        %td= t("my_events.event")
        %td= f.collection_select :event_id, @events, :id, :name, prompt: true, placeholder: t('my_events.actions.event')
      %tr
        %td{:colspan=>2}
          .form-actions
            = f.submit @my_event.new_record? ? t("buttons.create") : t("buttons.save"), :class => 'btn btn-primary btn-with-tooltip',"data-original-title" => t("messages.tooltips.save"),"data-my_eventment" => "bottom"
            = link_to t("buttons.cancel"), {:action => 'index'}

app/views/my_events/_list.html.haml
-if @my_events.count > 10
  .flickr_pagination
    = will_paginate @my_events

%table.table.table-striped
  %thead
    %th= t("my_events.name")
    -if current_user.admin?
      %th= t("my_events.user")
    %th= t("my_events.start_time")
    %th= t("my_events.place")
    %th= t("my_events.duration")
    %th= t("my_events.created_at")
    %th= t("my_events.actions.title")
  %tbody
    - @my_events.each do |row|
      -if can? :read, row
        %tr
          %td= link_to row.event.name.to_s, row.event
          -if current_user.admin?
            %td=row.user.email
          %td= row.event.start_time.strftime("%H:%M")
          %td
            %ul
              -row.event.places.find_each do |pl|
                %li=pl.name
          %td= row.event.time_diff
          %td= row.created_at.to_s
          %td
            - if can? :edit, MyEvent
              = link_to edit_my_event_path(row) do
                = bootstrap_icon "pencil", width: 15, height: 15, fill: "green"
            - if can? :delete, MyEvent
              = link_to my_event_path(row), :method => :delete,  data: { confirm: t('delete_confirm')} do
                = bootstrap_icon "trash", width: 15, height: 15, fill: "red"

-if @my_events.count > 10
  .flickr_pagination
    = will_paginate @my_events

-#permit(:name, :description, :contact_fio, :contact_address, :contact_email, :contact_phone)

app/views/my_events/edit.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/my_events/index.html.haml
.row
  .span9
    %h3.pull-left= t("my_events.list.title")
    -# = render_notice
    %span.top-panel-actions
      %table.table.borderless
        %tr
          %td
            = form_tag my_events_path, :method => 'get', :id => "my_events_search" do
              %p
                = text_field_tag :search, params[:search]
                = button_tag(type: "submit", class: "btn btn-default", :name => nil) do
                  = bootstrap_icon "search", width: 25, height: 25, fill: "blue"
          %td
            ="Найдено"
            =@my_events.count
            ="записей"
          %td
            - if can? :create, MyEvent
              = link_to new_my_event_path do
                -# = bootstrap_icon "file-plus", width: 15, height: 15, fill: "blue"
                = image_tag('register.png', :height => 25, :width => 95, :alt => "Записаться на мероприятие", :title => "Записаться на мероприятие")
            -# - if can? :export, MyEven
            -#   = link_to my_events_export_path do
            -#     = bootstrap_icon "download", width: 15, height: 15, fill: "blue"

    %span.marks-filter-target
      = render :partial => 'list', :locals => {:legend => t(".title")}

app/views/my_events/new.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/my_events/show.html.haml
-# -@id=params[:id]
%h1 Наименование проекта
%h2=@my_event.event.name.to_s
%table
  %tr
    %td=t("my_events.code")
    %td=@my_event.user.email
  %tr
    %td=t("my_events.full_name")
    %td=@my_event.event.name
%div
  = link_to "Вернуться", my_events_path, :class => "btn btn-primary btn-mini"